//
// Created by schrodinger on 2/23/20.
//

#ifndef SIMULATOR_SYSCALL_H
#define SIMULATOR_SYSCALL_H

#define SYSCALL_PRINT_CHAR 0
#define SYSCALL_PRINT_INT 1
#define SYSCALL_PRINT_STRING 2
#define SYSCALL_READ_CHAR 3
#define SYSCALL_READ_INT 4
#define SYSCALL_READ_STRING 5

#define SYSCALL_SBRK 6
#define SYSCALL_EXIT 7



#endif //SIMULATOR_SYSCALL_H
