//
// Created by schrodinger on 2/23/20.
//

#ifndef SIMULATOR_SYSCALL_H
#define SIMULATOR_SYSCALL_H

#define SYSCALL_PRINT_CHAR 0
#define SYSCALL_PRINT_INT 1
#define SYSCALL_PRINT_STRING 2
#define SYSCALL_READ_CHAR 3
#define SYSCALL_READ_INT 4
#define SYSCALL_READ_STRING 5

#define SYSCALL_MMAP 6
#define SYSCALL_EXIT 7
#define SYSCALL_MUNMAP 8
#define SYSCALL_OPEN 13
#define SYSCALL_READ 14
#define SYSCALL_WRITE 15
#define SYSCALL_CLOSE 16


#define SYSCALL_FAST_COPY 10000
#define SYSCALL_UI_OPEN_FILE 10001


#endif //SIMULATOR_SYSCALL_H
